// Seeds iniciais — usados quando o localStorage está vazio.
// Inspirados nos protótipos do Claude Design (Timeline ECONEXO / Mensagens ECONEXO).

export const SEED_POSTS = [
  {
    id: "p_seed_1",
    autor: {
      id: "u_mariana",
      nome: "Mariana Lopes",
      initials: "ML",
      color: "#0E8F5A",
      role: "Projetista fotovoltaica · CFT-SP",
      regiao: "Campinas · SP",
      verificado: true,
    },
    seguindo: false,
    tempo: "2 h",
    texto:
      "Entregamos mais um projeto residencial on-grid! 24 módulos de 550 Wp, 13,2 kWp gerando ~1.850 kWh/mês. Inversor monitorado e toda a instalação dentro da NR-35 para o trabalho em altura. Cliente já vendo ~92% de economia na conta. 🌞",
    foto: { rotulo: "usina solar · telhado residencial", kWp: "13,2 kWp", hue: 205 },
    tags: ["Solar residencial", "On-grid", "NR-35"],
    likes: 142,
    curtido: false,
    comentarios: [
      {
        id: "c_seed_1",
        nome: "Rafael Tavares",
        initials: "RT",
        color: "#C24A1E",
        texto: "Acabamento impecável. Qual marca do inversor?",
        tempo: "1 h",
      },
      {
        id: "c_seed_2",
        nome: "Mariana Lopes",
        initials: "ML",
        color: "#0E8F5A",
        texto: "Valeu! Growatt 12kW, monitoramento via app pro cliente.",
        tempo: "54 min",
      },
    ],
  },
  {
    id: "p_seed_2",
    autor: {
      id: "u_juliana",
      nome: "Juliana Prado",
      initials: "JP",
      color: "#7A2BC4",
      role: "Eng. de usinas (UFV) · CREA-MG",
      regiao: "Belo Horizonte · MG",
      verificado: true,
    },
    seguindo: true,
    tempo: "5 h",
    texto:
      "Comissionamento concluído da UFV Vale Verde: 2,4 MWp em solo, geração estimada de 4,1 GWh/ano. Foram 4.360 módulos e 3 meses de obra com a equipe homologada NR-10 e NR-35. Orgulho do time! 👇",
    foto: { rotulo: "usina solar em solo · 2,4 MWp", kWp: "2,4 MWp", hue: 225 },
    tags: ["Usina solar", "NR-10", "NR-35", "Minas Gerais"],
    likes: 318,
    curtido: true,
    comentarios: [],
  },
  {
    id: "p_seed_3",
    autor: {
      id: "u_rafael",
      nome: "Rafael Tavares",
      initials: "RT",
      color: "#C24A1E",
      role: "Instalador on-grid · NR-35",
      regiao: "Sorocaba · SP",
      verificado: true,
    },
    seguindo: false,
    tempo: "1 d",
    texto:
      "Limpeza e revisão de O&M num sistema comercial de 96 kWp que estava perdendo 18% de geração por sujidade. Depois da manutenção, voltou ao esperado. Procuro projetista pra um galpão de 220 kWp em Sorocaba — chama no privado!",
    foto: { rotulo: "manutenção · sistema comercial 96 kWp", kWp: "96 kWp", hue: 30 },
    tags: ["O&M", "Comercial", "Sorocaba"],
    likes: 87,
    curtido: false,
    comentarios: [],
  },
];

export const SEED_SUGERIDOS = [
  {
    id: "u_mariana",
    nome: "Mariana Lopes",
    initials: "ML",
    color: "#0E8F5A",
    role: "Projetista fotovoltaica",
    regiao: "Campinas · SP",
    verificado: true,
    seguindo: false,
  },
  {
    id: "u_rafael",
    nome: "Rafael Tavares",
    initials: "RT",
    color: "#C24A1E",
    role: "Instalador on-grid",
    regiao: "Sorocaba · SP",
    verificado: true,
    seguindo: false,
  },
  {
    id: "u_juliana",
    nome: "Juliana Prado",
    initials: "JP",
    color: "#7A2BC4",
    role: "Eng. de usinas (UFV)",
    regiao: "Belo Horizonte · MG",
    verificado: true,
    seguindo: false,
  },
];

export const SEED_DESTAQUES = [
  { id: "t1", titulo: "UFV Solar Vale Verde", meta: "2,4 MWp · Fazenda · MG", calor: "+312 interesses" },
  { id: "t2", titulo: "Condomínio Solar Aurora", meta: "186 kWp · Residencial · SP", calor: "+204 interesses" },
  { id: "t3", titulo: "Cold Storage Fotovoltaico", meta: "540 kWp · Indústria · PR", calor: "+158 interesses" },
];

export const SEED_CONVERSAS = [
  {
    id: "conv_u_juliana",
    participanteId: "u_juliana",
    nome: "Juliana Prado",
    initials: "JP",
    color: "#7A2BC4",
    role: "Eng. de usinas (UFV) · CREA-MG",
    regiao: "Belo Horizonte · MG",
    verificado: true,
    online: true,
    ultima: "Os módulos chegaram no canteiro 👍",
    tempo: "seg",
    naoLidas: 2,
    mensagens: [
      {
        id: "m_seed_1",
        de: "outro",
        tipo: "texto",
        tempo: "08:00",
        texto: "Bom dia! Como tá o andamento da estrutura de fixação?",
      },
      {
        id: "m_seed_2",
        de: "outro",
        tipo: "texto",
        tempo: "08:01",
        texto: "Os módulos chegaram no canteiro 👍",
      },
    ],
  },
  {
    id: "conv_u_mariana",
    participanteId: "u_mariana",
    nome: "Mariana Lopes",
    initials: "ML",
    color: "#0E8F5A",
    role: "Projetista fotovoltaica · CFT-SP",
    regiao: "Campinas · SP",
    verificado: true,
    online: false,
    ultima: "Valeu pela indicação! Já entrei em contato com o cliente.",
    tempo: "ontem",
    naoLidas: 0,
    mensagens: [
      {
        id: "m_seed_3",
        de: "outro",
        tipo: "texto",
        tempo: "14:30",
        texto: "Oi! Aquele cliente de Campinas ainda precisa de instalador?",
      },
      {
        id: "m_seed_4",
        de: "eu",
        tipo: "texto",
        tempo: "14:42",
        lido: true,
        texto: "Precisa sim! Pode passar meu contato pra ele tranquilo.",
      },
      {
        id: "m_seed_5",
        de: "outro",
        tipo: "texto",
        tempo: "15:01",
        texto: "Valeu pela indicação! Já entrei em contato com o cliente.",
      },
    ],
  },
];
